// Tauri Commands module

pub mod backup;
pub mod provider;
pub mod model;
pub mod mcp;
pub mod skills;
pub mod rule;
pub mod status;
pub mod settings;
pub mod ohmy;
pub mod deeplink;
pub mod claude_code;
pub mod codex;
pub mod gemini;
pub mod prompts;
pub mod speedtest;
pub mod usage;
pub mod proxy;
pub mod open_switch;

pub use backup::*;
pub use provider::*;
pub use model::*;
pub use mcp::*;
pub use skills::*;
pub use rule::*;
pub use status::*;
pub use settings::*;
pub use ohmy::*;
pub use deeplink::*;
pub use claude_code::*;
pub use codex::*;
pub use gemini::*;
pub use prompts::*;
pub use speedtest::*;
pub use usage::*;
pub use proxy::*;
pub use open_switch::*;
